extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_Schachbrett_Muster_i8[];
extern Vtx castle_grounds_dl_General_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_General_mesh_layer_1_vtx_0[14];
extern Gfx castle_grounds_dl_General_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_checker[];
extern Gfx mat_revert_castle_grounds_dl_checker[];
extern Gfx castle_grounds_dl_General_mesh_layer_1[];
