#include "src/game/envfx_snow.h"

const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_1___eye_half_v3_001_0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_1___eye_half_v3_001_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_2___eye_closed_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_3___eye_left_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_3___eye_left_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_0___eye_open_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_0___eye_open_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_5___eye_up_v3_001_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_5___eye_up_v3_001_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_6___eye_down_v3_001_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_6___eye_down_v3_001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_7___eye_X_v3_001_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_7___eye_X_v3_001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_mario_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt1),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt2),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt3),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt4),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt5),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt6),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt1_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_Switch_Option_metal_mario_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Switch_Option_Capless_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Switch_Option_Capless_Head_DL_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_Switch_Option_metal_mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_Switch_Option_metal_mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_Switch_Option_metal_mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_Switch_Option_metal_mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_Switch_Option_metal_mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Switch_Option_Capless_Head_DL_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Switch_Option_Capless_Head_DL_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Switch_Option_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, sueli_Switch_Option_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Head_DL_mesh_layer_1),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Head_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_cap_off),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Switch_Option_Left_Arm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sueli_Switch_Option_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Left_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_left_hand_open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Switch_Option_Right_Arm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sueli_Switch_Option_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_open),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_peace),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_cap),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1_jump_sueli_Switch_Option_metal_mario_right_hand_wing_cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Switch_Option_Left_Thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, sueli_Switch_Option_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, sueli_Switch_Option_Left_Foot_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Switch_Option_Right_Thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, sueli_Switch_Option_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Right_Foot_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_metal_mario[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Switch_Option_Butt_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_move_mario_part_from_parent),
						GEO_ASM(0, geo_mario_tilt_torso),
						GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, sueli_Switch_Option_Torso_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_head_rotation),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Head_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Head_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sueli_Switch_Option_metal_mario_cap_off),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Right_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
										GEO_OPEN_NODE(),
											GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Switch_Option_Left_Wing_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, 79, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Switch_Option_Left_Arm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sueli_Switch_Option_Left_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Left_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, sueli_Switch_Option_metal_mario_left_hand_open),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Switch_Option_Right_Arm_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sueli_Switch_Option_Right_Forearm_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(0, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(0, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Right_Hand_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
														GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, sueli_Switch_Option_metal_mario_right_hand_open),
												GEO_BRANCH(1, sueli_Switch_Option_metal_mario_right_hand_peace),
												GEO_BRANCH(1, sueli_Switch_Option_metal_mario_right_hand_cap),
												GEO_BRANCH(1, sueli_Switch_Option_metal_mario_right_hand_wing_cap),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Switch_Option_Left_Thigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, sueli_Switch_Option_Left_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, sueli_Switch_Option_Left_Foot_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Switch_Option_Right_Thigh_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, sueli_Switch_Option_Right_Leg_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
									GEO_OPEN_NODE(),
										GEO_ASM(2, geo_mario_hand_foot_scaler),
										GEO_SCALE(LAYER_FORCE, 65536),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Switch_Option_Right_Foot_DL_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt2_Cap_Effect_Switch_opt1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_1___eye_half_v3_001_0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_1___eye_half_v3_001_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_2___eye_closed_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_3___eye_left_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_3___eye_left_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_0___eye_open_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_0___eye_open_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_5___eye_up_v3_001_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_5___eye_up_v3_001_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_6___eye_down_v3_001_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_6___eye_down_v3_001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1_mat_override_face_7___eye_X_v3_001_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4_mat_override_face_7___eye_X_v3_001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_cap_off[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Capless_Head_DL_mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt1),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt2),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt3),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt4),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt5),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt6),
			GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt1_Eye_State_Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_left_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Left_Hand_Open_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Right_Hand_Peace_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Right_Hand_Cap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_wing_cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, sueli_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Switch_Option_Right_Hand_Wing_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1_mat_override_face_1___eye_half_v3_001_0),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4_mat_override_face_1___eye_half_v3_001_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4_mat_override_face_2___eye_closed_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1_mat_override_face_3___eye_left_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4_mat_override_face_3___eye_left_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1_mat_override_face_0___eye_open_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4_mat_override_face_0___eye_open_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1_mat_override_face_5___eye_up_v3_001_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4_mat_override_face_5___eye_up_v3_001_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1_mat_override_face_6___eye_down_v3_001_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4_mat_override_face_6___eye_down_v3_001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1_mat_override_face_7___eye_X_v3_001_6),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4_mat_override_face_7___eye_X_v3_001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 68, 0, 0, sueli_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Head_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt1),
											GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt2),
											GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt3),
											GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt4),
											GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt5),
											GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt6),
											GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_0_Cap_State_Switch_opt0_Eye_State_Switch_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_cap_off),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, 79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Left_Arm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sueli_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Left_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_left_hand_open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Right_Arm_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 65, 0, 0, sueli_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Right_Hand_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_open),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_peace),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_cap),
										GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1_jump_sueli_mario_right_hand_wing_cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Left_Thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, sueli_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 67, 0, 0, sueli_Left_Foot_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, sueli_Right_Thigh_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 89, 0, 0, sueli_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_Right_Foot_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1_mat_override_face_1___eye_half_v3_001_0),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4_mat_override_face_1___eye_half_v3_001_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1_mat_override_face_2___eye_closed_v3_001_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4_mat_override_face_2___eye_closed_v3_001_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1_mat_override_face_3___eye_left_v3_001_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4_mat_override_face_3___eye_left_v3_001_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1_mat_override_face_0___eye_open_v3_001_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4_mat_override_face_0___eye_open_v3_001_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1_mat_override_face_5___eye_up_v3_001_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4_mat_override_face_5___eye_up_v3_001_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1_mat_override_face_6___eye_down_v3_001_5),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4_mat_override_face_6___eye_down_v3_001_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1_mat_override_face_7___eye_X_v3_001_6),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4_mat_override_face_7___eye_X_v3_001_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout sueli_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(99, 179, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(LAYER_OPAQUE + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_ALPHA + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_TRANSPARENT + 3, geo_mario_set_player_colors),
GEO_ASM(LAYER_TRANSPARENT_DECAL + 3, geo_mario_set_player_colors),

				GEO_ASM(LAYER_OPAQUE << 2, geo_mirror_mario_backface_culling),
GEO_ASM(LAYER_ALPHA << 2, geo_mirror_mario_backface_culling),
GEO_ASM(LAYER_TRANSPARENT << 2, geo_mirror_mario_backface_culling),
GEO_ASM(LAYER_TRANSPARENT_DECAL << 2, geo_mirror_mario_backface_culling),

				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Butt_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ASM(0, geo_move_mario_part_from_parent),
								GEO_ASM(0, geo_mario_tilt_torso),
								GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 68, 0, 0, sueli_Torso_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, NULL),
										GEO_OPEN_NODE(),
											GEO_ASM(0, geo_mario_head_rotation),
											GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
											GEO_OPEN_NODE(),
												GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
												GEO_OPEN_NODE(),
													GEO_NODE_START(),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Head_DL_mesh_layer_1),
																GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Head_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt1),
															GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt2),
															GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt3),
															GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt4),
															GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt5),
															GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt6),
															GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt0_0_Cap_State_Switch_opt0_Eye_State_Switch_opt7),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
													GEO_BRANCH(1, sueli_mario_cap_off),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, -126, 15, -33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Right_Wing_DL_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_TRANSLATE_ROTATE(LAYER_FORCE, 142, -51, 126, -15, 33, -133),
												GEO_OPEN_NODE(),
													GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_Left_Wing_DL_mesh_layer_4),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, 79, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Left_Arm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sueli_Left_Forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(1, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(1, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Left_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, sueli_mario_left_hand_open),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 68, -10, -79, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Right_Arm_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 65, 0, 0, sueli_Right_Forearm_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_SWITCH_CASE(0, geo_switch_mario_hand),
													GEO_OPEN_NODE(),
														GEO_NODE_START(),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, NULL),
															GEO_OPEN_NODE(),
																GEO_ASM(0, geo_mario_hand_foot_scaler),
																GEO_SCALE(LAYER_FORCE, 65536),
																GEO_OPEN_NODE(),
																	GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Right_Hand_DL_mesh_layer_1),
																GEO_CLOSE_NODE(),
																GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_BRANCH(1, sueli_mario_right_hand_open),
														GEO_BRANCH(1, sueli_mario_right_hand_peace),
														GEO_BRANCH(1, sueli_mario_right_hand_cap),
														GEO_BRANCH(1, sueli_mario_right_hand_wing_cap),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, 42, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Left_Thigh_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, sueli_Left_Leg_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, sueli_Left_Foot_mesh_layer_1),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 13, -8, -42, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, sueli_Right_Thigh_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 89, 0, 0, sueli_Right_Leg_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 67, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(2, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_Right_Foot_DL_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, sueli_3_Cap_Effect_Switch_opt1),
					GEO_BRANCH(1, sueli_metal_mario),
					GEO_BRANCH(1, sueli_metal_mario),
				GEO_CLOSE_NODE(),
				GEO_ASM((LAYER_OPAQUE << 2) | 1, geo_mirror_mario_backface_culling),
GEO_ASM((LAYER_ALPHA << 2) | 1, geo_mirror_mario_backface_culling),
GEO_ASM((LAYER_TRANSPARENT << 2) | 1, geo_mirror_mario_backface_culling),
GEO_ASM((LAYER_TRANSPARENT_DECAL << 2) | 1, geo_mirror_mario_backface_culling),

			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, sueli_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, sueli_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, sueli_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
